/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/action/forward_dynamics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forward Dynamics */
        post: operations["forward_dynamics_v1_action_forward_dynamics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/action/inverse_dynamics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inverse Dynamics */
        post: operations["inverse_dynamics_v1_action_inverse_dynamics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/action/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Policy */
        post: operations["policy_v1_action_policy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generation/i2v": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** I2V */
        post: operations["i2v_v1_generation_i2v_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generation/t2i": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** T2I */
        post: operations["t2i_v1_generation_t2i_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generation/t2v": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** T2V */
        post: operations["t2v_v1_generation_t2v_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generation/t2v_audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** T2V Audio */
        post: operations["t2v_audio_v1_generation_t2v_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Job */
        post: operations["submit_job_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_v1_jobs__job_id__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/trajectory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trajectory */
        get: operations["get_trajectory_v1_jobs__job_id__trajectory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reason": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reason */
        post: operations["reason_v1_reason_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionBody
         * @description A typed action request (forward_dynamics/inverse_dynamics/policy). The route fixes the mode.
         */
        ActionBody: {
            /**
             * Checkpoint
             * @description Optional served-checkpoint label; single-checkpoint deployments serve the deployed checkpoint implicitly. If given, must equal the deployed label (else 422).
             */
            checkpoint?: string | null;
            /**
             * Chunk Size
             * @description Action transition count (the 16–400 rollout window).
             */
            chunk_size: number;
            /**
             * Domain Name
             * @description Embodiment domain (e.g. 'agibotworld' 29-D, 'av' 9-D).
             */
            domain_name: string;
            /** @description Inline conditioning image/video (base64). */
            image?: components["schemas"]["InlineMedia"] | null;
            /**
             * Image Path
             * @description Trusted-volume conditioning image path (FD/policy).
             */
            image_path?: string | null;
            /**
             * Prompt
             * @description Optional instruction (policy).
             */
            prompt?: string | null;
            /**
             * Raw Actions
             * @description Forward-dynamics driving tensor [T, raw_dim].
             */
            raw_actions?: unknown[] | null;
            /**
             * Resolution Tier
             * @description Conditioning resolution tier ∈ {256,480,704,720}.
             * @default 480
             */
            resolution_tier: number;
            /**
             * Seed
             * @description Deterministic seed (INV-10).
             * @default 123
             */
            seed: number;
            /**
             * Video Path
             * @description Trusted-volume conditioning video path (ID).
             */
            video_path?: string | null;
            /**
             * View Point
             * @description Camera view point.
             * @default ego_view
             */
            view_point: string;
        };
        /**
         * ErrorModel
         * @description Structured error body for the standard HTTP error contract (E4).
         */
        ErrorModel: {
            /**
             * Code
             * @description Machine-readable error code, e.g. 'invalid_input'.
             */
            code: string;
            /**
             * Details
             * @description Optional structured context.
             * @default null
             */
            details: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description Human-readable error message.
             */
            message: string;
        };
        /**
         * GenerationBody
         * @description A typed generation request (t2i/t2v/i2v/t2v_audio). The route fixes the mode + mode-specifics.
         */
        GenerationBody: {
            /**
             * Checkpoint
             * @description Optional served-checkpoint label; single-checkpoint deployments serve the deployed checkpoint implicitly. If given, must equal the deployed label (else 422).
             */
            checkpoint?: string | null;
            /**
             * Height
             * @description Frame height (∈ the resolution families).
             */
            height?: number | null;
            /** @description Inline conditioning image (base64; i2v). */
            image?: components["schemas"]["InlineMedia"] | null;
            /**
             * Image Path
             * @description Trusted-volume conditioning image path (i2v).
             */
            image_path?: string | null;
            /**
             * Negative Prompt
             * @description Optional negative prompt.
             */
            negative_prompt?: string | null;
            /**
             * Num Frames
             * @description Frame count (t2i is forced to 1); ≤ the public cap.
             */
            num_frames?: number | null;
            /**
             * Num Inference Steps
             * @description Denoising steps.
             */
            num_inference_steps?: number | null;
            /**
             * Prompt
             * @description The generation prompt.
             */
            prompt: string;
            /**
             * Resolution
             * @description Square resolution ∈ {256,480,720}. When width/height are omitted, video modes (t2v/i2v/t2v_audio) default to 1280×720 and t2i defaults to 480.
             */
            resolution?: number | null;
            /**
             * Seed
             * @description Deterministic seed (INV-10).
             * @default 123
             */
            seed: number;
            /**
             * Width
             * @description Frame width (∈ the resolution families).
             */
            width?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Health payload for the liveness/readiness endpoints (G3/RK-07).
         */
        HealthStatus: {
            /**
             * Detail
             * @description Optional human-readable context.
             */
            detail?: string | null;
            /**
             * Status
             * @description 'live' | 'warming' | 'ready'.
             */
            status: string;
        };
        /**
         * InlineMedia
         * @description Optional inline conditioning media for a job (base64 — the dep-free upload path; S6).
         *
         *     The production multipart upload via the webui BFF is S7/S8; S6 validates either this inline blob
         *     or a trusted-volume path carried in ``params``.
         */
        InlineMedia: {
            /**
             * Data Base64
             * @description Base64-encoded conditioning media bytes.
             */
            data_base64: string;
            /**
             * Kind
             * @description 'image' | 'video' | 'audio'.
             */
            kind: string;
        };
        /**
         * Job
         * @description An async job record (202 + job id + SSE + artifact fetch; INV-5).
         *
         *     Schema stub only in S1 — no job *endpoints* exist yet (those are S6).
         */
        Job: {
            /**
             * Artifact Url
             * @description Artifact location once succeeded.
             * @default null
             */
            artifact_url: string | null;
            /**
             * Created At
             * @description ISO-8601 creation timestamp.
             */
            created_at: string;
            /**
             * @description Populated when status is 'failed'.
             * @default null
             */
            error: components["schemas"]["ErrorModel"] | null;
            /**
             * Id
             * @description Opaque job identifier.
             */
            id: string;
            /**
             * Mode
             * @description Public mode, e.g. 't2i' / 't2v' / 'i2v' / 'reason' / 'action'.
             */
            mode: string;
            /**
             * Precision
             * @description The served checkpoint precision ('nvfp4'/'fp8'), reported on success (S7).
             * @default null
             */
            precision: string | null;
            /**
             * Progress
             * @description Fractional progress in [0, 1].
             * @default 0
             */
            progress: number;
            status: components["schemas"]["JobStatus"];
            /**
             * Trajectory Url
             * @description Action trajectory location (FD/policy rollout + ID), when present (S7).
             * @default null
             */
            trajectory_url: string | null;
        };
        /**
         * JobStatus
         * @description Lifecycle states for an async media/action job (INV-5).
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * JobSubmit
         * @description A media/action job submission (INV-5).
         */
        JobSubmit: {
            /** @description Optional inline conditioning media (base64). */
            media?: components["schemas"]["InlineMedia"] | null;
            /**
             * Mode
             * @description Job mode: t2i/t2v/i2v/t2v_audio or forward_dynamics/inverse_dynamics/policy.
             */
            mode: string;
            /**
             * Params
             * @description Mode-specific params (prompt, resolution, num_frames, embodiment, conditioning paths).
             */
            params?: {
                [key: string]: unknown;
            };
        };
        /**
         * ReasoningBody
         * @description A typed reasoning request (text+image/video → text, streamed as SSE).
         */
        ReasoningBody: {
            /**
             * Image Path
             * @description Trusted-volume conditioning image path (EC-R2).
             */
            image_path?: string | null;
            /**
             * Max Output Tokens
             * @description Output token budget. Omit/null = bounded only by the backend context window (≤ max_context_tokens − prompt). If supplied, it must fit the context window.
             */
            max_output_tokens?: number | null;
            /**
             * Prompt
             * @description The reasoning prompt.
             */
            prompt: string;
            /**
             * Video Path
             * @description Trusted-volume conditioning video path (EC-R3).
             */
            video_path?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forward_dynamics_v1_action_forward_dynamics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inverse_dynamics_v1_action_inverse_dynamics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_v1_action_policy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    i2v_v1_generation_i2v_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    t2i_v1_generation_t2i_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    t2v_v1_generation_t2v_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    t2v_audio_v1_generation_t2v_audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    ready_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    submit_job_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_v1_jobs__job_id__artifact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trajectory_v1_jobs__job_id__trajectory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reason_v1_reason_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasoningBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
